// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGztovGLPKuNp0wJz37z2kgM9wxRK4FX0',
    appId: '1:503218785782:web:a75423e2f92bcd54ae0bd7',
    messagingSenderId: '503218785782',
    projectId: 'cobaaja-b3521',
    authDomain: 'cobaaja-b3521.firebaseapp.com',
    databaseURL: 'https://cobaaja-b3521-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cobaaja-b3521.appspot.com',
    measurementId: 'G-933W953J43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6sGYcCEP_wZ3MIIw21uGiXGEv7WynrJY',
    appId: '1:503218785782:android:0b2d8356efa84c4aae0bd7',
    messagingSenderId: '503218785782',
    projectId: 'cobaaja-b3521',
    databaseURL: 'https://cobaaja-b3521-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cobaaja-b3521.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9XfNgxsvpQrT3Bx88dpk1xSaQGyB6OEg',
    appId: '1:503218785782:ios:dc4eca628101e310ae0bd7',
    messagingSenderId: '503218785782',
    projectId: 'cobaaja-b3521',
    databaseURL: 'https://cobaaja-b3521-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cobaaja-b3521.appspot.com',
    androidClientId: '503218785782-rp5aucekdhlgcemig89gl7gbbjk5lkbh.apps.googleusercontent.com',
    iosClientId: '503218785782-la82la84fb4vlbtnimh1l51ij0537gc6.apps.googleusercontent.com',
    iosBundleId: 'com.Ay.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9XfNgxsvpQrT3Bx88dpk1xSaQGyB6OEg',
    appId: '1:503218785782:ios:dc4eca628101e310ae0bd7',
    messagingSenderId: '503218785782',
    projectId: 'cobaaja-b3521',
    databaseURL: 'https://cobaaja-b3521-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cobaaja-b3521.appspot.com',
    androidClientId: '503218785782-rp5aucekdhlgcemig89gl7gbbjk5lkbh.apps.googleusercontent.com',
    iosClientId: '503218785782-la82la84fb4vlbtnimh1l51ij0537gc6.apps.googleusercontent.com',
    iosBundleId: 'com.Ay.chatapp',
  );
}
